### PR TITLE
updated gin to use gopkg v1

### PR DESCRIPTION
**Pull request by phenixrizen**

### CODE REVIEW

**Comment by ITSecMedia** [comment]
Cheers, finally somebody did it, I've been waiting for that one :)

**Comment by appleboy** [comment]
@phenixrizen @ITSecMedia we also need to update `glide` config. I will do it now.

**Comment by appleboy** [comment]
Fixed and merged in #49 cc @phenixrizen @ITSecMedia

**Comment by appleboy** [comment]
Also bump to v2.1.2

**Pull request closed without merging**
